services:
  app:
    image: hello-front-dev
    build:
      context: .
      dockerfile: dev.Dockerfile
    volumes:
      - ./:/urs/src/app
    ports:
      - 5173:5173
    container_name: hello-front-dev